apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-jkpg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-jkpg
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-jkpg
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-jkpg
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-jkpg
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dhtf-tenant/rhtap-demo-app/hacbs-test-project-jkpg@sha256:46391728a3f08b735ec96d95805780cb3f8e9594124c2c0d92b2b1bbcc67083c
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
